services:
  ank-server:
    image: ghcr.io/gustavo324234/aegis-ank:latest
    build:
      context: ../Aegis-ANK
      dockerfile: Dockerfile
      args:
        FEATURES: ${AEGIS_FEATURES:-}
    container_name: aegis-ank
    profiles: ["cpu"]
    restart: unless-stopped
    user: "0"
    env_file:
      - .env
    environment:
      - RUST_LOG=info
    volumes:
      - ./users:/app/users
      - ./models:/app/models
      - ank-data:/app/data
    networks:
      - aegis_net
    expose:
      - "50051"

  ank-server-gpu:
    image: ghcr.io/gustavo324234/aegis-ank:latest
    build:
      context: ../Aegis-ANK
      dockerfile: Dockerfile
      args:
        FEATURES: ${AEGIS_FEATURES:-}
    container_name: aegis-ank
    profiles: ["gpu"]
    restart: unless-stopped
    user: "0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
    environment:
      - RUST_LOG=info
    volumes:
      - ./users:/app/users
      - ./models:/app/models
      - ank-data:/app/data
    networks:
      - aegis_net
    expose:
      - "50051"

  aegis-shell:
    image: ghcr.io/gustavo324234/aegis-shell:latest
    build:
      context: ../Aegis-Shell
      dockerfile: Dockerfile
    container_name: aegis-shell
    profiles: ["frontend"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ANK_TARGET=ank-server:50051
    ports:
      - "8000:8000"
    depends_on:
      - ank-server
    volumes:
      - ank-data:/app/data
    networks:
      - aegis_net

volumes:
  ank-data:

networks:
  aegis_net:
    driver: bridge
